export const kSubscriptionSource = [
  'unknown',
  'entries',
  'prompts',
  'menu',
  'regeneratePrompts',
  'regenerateSuggestions',
  'settingsCloudSync',
  'onboarding',
  'bookmarks',
  'bookmarkButton',
  'voice',
  'reminder',
  'digDeeperLimitReached',
  'subscriptionPage',
  'weeklyReflection',
  'weeklyInsight',
  'askRosebud',
  'yearInReview',
  'settingsMemory',
] as const
